module.exports = {
    "name": "Drawsum!",
    "eventPrefix": "drawsum",
    "description": "See how well other people can guess what you're drawing!",
    "minimumPlayers": 2,
    "maximumPlayers": 10,
    "instructions": "Draw a prompt. Whoever guesses what you are trying to draw gets points.",
    "colors": ["black", "white", "tan", "sienna", "red", "orange", "yellow", "green", "blue", "indigo", "purple", "pink"],
    "sizes": [5, 15, 30, 50, 80],
    "codeLength": 5,
    "roundsPerPlayer": 3,
    "roundTimer": 60,
    "interRoundTimer": 2,
    "baseScore": 10,
    "wordChoicesPerRound": 3,
}