'use strict';

module.exports= {
	applestoapplesInitState,
	applestoapplesJoinGame,
	applestoapplesReadyUp
	
}

function applestoapplesInitState(username, socketId) {
	return createGameState(username, socketId);
}

function createGameState(username, socketId) {
	
	return {
		players: 
		[
			{
				username,
				socketId,
				ready: false,
				judge: false,
				score: 0,
				

			}
		],
		
		greencards:
		[
			{name : 'awkward', description: ''},
			{name : 'cowardly', description: ''},
			{name : 'delightful', description: ''},
			{name : 'boring', description: ''},
			{name : 'absurd', description: ''},
			{name : 'busy', description: ''},
			{name : 'chunky', description: ''},
			{name : 'crazed', description: ''},
			{name : 'dangerous', description: ''},
			{name : 'cuddly', description: ''},
			{name : 'cute', description: ''},
			{name : 'dainty', description: ''},
			{name : 'dead', description: ''},
			{name : 'cosmic', description: ''},
			{name : 'appetizing', description: ''},
			{name : 'creative', description: ''},
			{name : 'deadly', description: ''},
			{name : 'addictive', description: ''},
			{name : 'adorable', description: ''},
			{name : 'cold', description: ''},
			{name : 'cranky', description: ''},
			{name : 'arrogant', description: ''},
			{name : 'bright', description: ''},
			{name : 'bold', description: ''},
			{name : 'brilliant', description: ''},
			{name : 'calm', description: ''},
			{name : 'delicate', description: ''},
			{name : 'ancient', description: ''},
			{name : 'casual', description: ''},
			{name : 'charismatic', description: ''},
			{name : 'comical', description: ''},
			{name : 'cool', description: ''},
			{name : 'annoying', description: ''},
			{name : 'clean', description: ''},
			{name : 'cosmopolitan', description: ''},
			{name : 'cruel', description: ''},
			{name : 'aged', description: ''},
			{name : 'American', description: ''},
			{name : 'animated', description: ''},
			{name : 'awesome', description: ''},
			{name : 'believable', description: ''},
			{name : 'bogus', description: ''},
			{name : 'classic', description: ''},
			{name : 'crazy', description: ''},
			{name : 'delicious', description: ''},
			{name : 'corrupt', description: ''},
			{name : 'charming', description: ''},
			{name : 'cheesy', description: ''},
			{name : 'chewy', description: ''},
			{name : 'comfortable', description: ''},
			{name : 'complicated', description: ''},
			{name : 'confused', description: ''},
			{name : 'courageous', description: ''},
			{name : 'boisterous', description: ''},
			{name : 'clueless', description: ''},
			{name : 'colorful', description: ''},
			{name : 'creepy', description: ''},
			{name : 'disturbing', description: ''},
			{name : 'exhausting', description: ''},
			{name : 'hard-working', description: ''},
			{name : 'healthy', description: ''},
			{name : 'honorable', description: ''},
			{name : 'innocent', description: ''},
			{name : 'insulting', description: ''},
			{name : 'naîve', description: ''},
			{name : 'shallow', description: ''},
			{name : 'silly', description: ''},
			{name : 'smelly', description: ''},
			{name : 'unbelievable', description: ''},
			{name : 'dramatic', description: ''},
			{name : 'explosive', description: ''},
			{name : 'extreme', description: ''},
			{name : 'glamorous', description: ''},
			{name : 'rare', description: ''},
			{name : 'repulsive', description: ''},
			{name : 'risky', description: ''},
			{name : 'spunky', description: ''},
			{name : 'unnatural', description: ''},
			{name : 'dignified', description: ''},
			{name : 'eccentric', description: ''},
			{name : 'fabulous', description: ''},
			{name : 'foreign', description: ''},
			{name : 'funky', description: ''},
			{name : 'heartless', description: ''},
			{name : 'hot', description: ''},
			{name : 'inspirational', description: ''},
			{name : 'legendary', description: ''},
			{name : 'misunderstood', description: ''},
			{name : 'nasty', description: ''},
			{name : 'obnoxious', description: ''},
			{name : 'painful', description: ''},
			{name : 'primitive', description: ''},
			{name : 'radical', description: ''},
			{name : 'revolutionary', description: ''},
			{name : 'scary', description: ''},
			{name : 'sharp', description: ''},
			{name : 'technological', description: ''},
			{name : 'tough', description: ''},
			{name : 'trustworthy', description: ''},
			{name : 'unforgettable', description: ''},
			{name : 'frazzled', description: ''},
			{name : 'global', description: ''},
			{name : 'intelligent', description: ''},
			{name : 'loud', description: ''},
			{name : 'pathetic', description: ''},
			{name : 'rough', description: ''},
			{name : 'smooth', description: ''},
			{name : 'weird', description: ''},
			{name : 'depressing', description: ''},
			{name : 'expensive', description: ''},
			{name : 'principled', description: ''},
			{name : 'relaxing', description: ''},
			{name : 'sexy', description: ''},
			{name : 'unscrupulous', description: ''},
			{name : 'visionary', description: ''},
			{name : 'woebegone', description: ''},
			{name : 'European', description: ''},
			{name : 'exciting', description: ''},
			{name : 'fancy', description: ''},
			{name : 'flirtatious', description: ''},
			{name : 'frivolous', description: ''},
			{name : 'influential', description: ''},
			{name : 'juicy', description: ''},
			{name : 'natural', description: ''},
			{name : 'stereotyped', description: ''},
			{name : 'unusual', description: ''},
			{name : 'virtuous', description: ''},
			{name : 'desperate', description: ''},
			{name : 'distinguished', description: ''},
			{name : 'dreamy', description: ''},
			{name : 'earthy', description: ''},
			{name : 'filthy', description: ''},
			{name : 'frightening', description: ''},
			{name : 'furious', description: ''},
			{name : 'idiotic', description: ''},
			{name : 'scenic', description: ''},
			{name : 'stunning', description: ''},
			{name : 'sweet', description: ''},
			{name : 'temperamental', description: ''},
			{name : 'dysfunctional', description: ''},
			{name : 'graceful', description: ''},
			{name : 'horrifying', description: ''},
			{name : 'insane', description: ''},
			{name : 'manly', description: ''},
			{name : 'mystical', description: ''},
			{name : 'overwhelming', description: ''},
			{name : 'popular', description: ''},
			{name : 'refined', description: ''},
			{name : 'rich', description: ''},
			{name : 'senseless', description: ''},
			{name : 'sensitive', description: ''},
			{name : 'shocking', description: ''},
			{name : 'spooky', description: ''},
			{name : 'demanding', description: ''},
			{name : 'dirty', description: ''},
			{name : 'elitist', description: ''},
			{name : 'friendly', description: ''},
			{name : 'glorious', description: ''},
			{name : 'goody-goody', description: ''},
			{name : 'important', description: ''},
			{name : 'industrious', description: ''},
			{name : 'melodramatic', description: ''},
			{name : 'patriotic', description: ''},
			{name : 'realistic', description: ''},
			{name : 'responsible', description: ''},
			{name : 'sappy', description: ''},
			{name : 'shiny', description: ''},
			{name : 'snappy', description: ''},
			{name : 'spicy', description: ''},
			{name : 'wild', description: ''},
			{name : 'emotional', description: ''},
			{name : 'eternal', description: ''},
			{name : 'fantastic', description: ''},
			{name : 'feminine', description: ''},
			{name : 'fuzzy', description: ''},
			{name : 'ordinary', description: ''},
			{name : 'peaceful', description: ''},
			{name : 'radiant', description: ''},
			{name : 'saintly', description: ''},
			{name : 'speedy', description: ''},
			{name : 'tame', description: ''},
			{name : 'touchy-feely', description: ''},
			{name : 'zany', description: ''},
			{name : 'fragrant', description: ''},
			{name : 'funny', description: ''},
			{name : 'irresistible', description: ''},
			{name : 'luscious', description: ''},
			{name : 'magical', description: ''},
			{name : 'masculine', description: ''},
			{name : 'miserable', description: ''},
			{name : 'odd', description: ''},
			{name : 'offensive ', description: ''},
			{name : 'playful', description: ''},
			{name : 'puffy', description: ''},
			{name : 'ridiculous', description: ''},
			{name : 'spiritual', description: ''},
			{name : 'sultry', description: ''},
			{name : 'talented', description: ''},
			{name : 'worldly', description: ''},
			{name : 'handsome', description: ''},
			{name : 'intense', description: ''},
			{name : 'meek', description: ''},
			{name : 'outrageous', description: ''},
			{name : 'pure', description: ''},
			{name : 'shy', description: ''},
			{name : 'soft', description: ''},
			{name : 'hopeless', description: ''},
			{name : 'neat', description: ''},
			{name : 'neglected', description: ''},
			{name : 'normal', description: ''},
			{name : 'organic', description: ''},
			{name : 'perfect', description: ''},
			{name : 'philosophical', description: ''},
			{name : 'phony', description: ''},
			{name : 'smart', description: ''},
			{name : 'timeless', description: ''},
			{name : 'useless', description: ''},
			{name : 'wicked', description: ''},
			{name : 'dull', description: ''},
			{name : 'harmful', description: ''},
			{name : 'hilarious', description: ''},
			{name : 'lovable', description: ''},
			{name : 'lucky', description: ''},
			{name : 'nerdy', description: ''},
			{name : 'sensual', description: ''},
			{name : 'swift', description: ''},
			{name : 'unhealthy', description: ''},
			{name : 'violent', description: ''},
			{name : 'easy', description: ''},
			{name : 'fake', description: ''},
			{name : 'glitzy', description: ''},
			{name : 'powerful', description: ''},
			{name : 'quiet', description: ''},
			{name : 'selfish', description: ''},
			{name : 'witty', description: ''},
			{name : 'exquisite', description: ''},
			{name : 'fresh', description: ''},
			{name : 'haunting', description: ''},
			{name : 'hostile', description: ''},
			{name : 'irritating', description: ''},
			{name : 'lazy', description: ''},
			{name : 'luxurious', description: ''},
			{name : 'mischievous', description: ''},
			{name : 'mysterious', description: ''},
			{name : 'profound', description: ''},
			{name : 'refreshing', description: ''},
			{name : 'squeaky clean', description: ''},
			{name : 'twisted', description: ''},
			{name : 'unreal', description: ''},
		],
		cards:
		[	
			{name : '4th of July '  , description: ''},
			{name : 'a car crash '  , description: ''},
			{name : 'a cheap motel '  , description: ''},
			{name : 'a dozen red roses '  , description: ''},
			{name : 'a full moon '  , description: ''},
			{name : 'a haunted house '  , description: ''},
			{name : 'a high school bathroom '  , description: ''},
			{name : 'a honeymoon '  , description: ''},
			{name : 'a locker room '  , description: ''},
			{name : 'a morgue '  , description: ''},
			{name : 'a nine iron '  , description: ''},
			{name : 'a schoolbus '  , description: ''},
			{name : 'a sunset '  , description: ''},
			{name : 'a treehouse '  , description: ''},
			{name : 'a used car lot '  , description: ''},
			{name : 'Abraham Lincoln'  , description: ''},
			{name : 'Adam Sandler'  , description: ''},
			{name : 'Adolf Hitler '  , description: ''},
			{name : 'AIDS '  , description: ''},
			{name : 'airline food '  , description: ''},
			{name : 'Al Pacino'  , description: ''},
			{name : 'Albert Einstein '  , description: ''},
			{name : 'Alfred Hitchcock '  , description: ''},
			{name : 'alien abductions '  , description: ''},
			{name : 'Americans'  , description: ''},
			{name : 'amputations'  , description: ''},
			{name : 'Andy Warhol'  , description: ''},
			{name : 'angry hornets '  , description: ''},
			{name : 'Anne Frank '  , description: ''},
			{name : 'Antarctica'  , description: ''},
			{name : 'Anthony Hopkins '  , description: ''},
			{name : 'apple pie'  , description: ''},
			{name : 'apples'  , description: ''},
			{name : 'armed robbery'  , description: ''},
			{name : 'assembly lines '  , description: ''},
			{name : 'Atlantis'  , description: ''},
			{name : 'atomic bombs '  , description: ''},
			{name : 'Attack on Pearl Harbor '  , description: ''},
			{name : 'audit '  , description: ''},
			{name : 'Austin Powers'  , description: ''},
			{name : 'Australian outback '  , description: ''},
			{name : 'Babe Ruth'  , description: ''},
			{name : 'babies  '  , description: ''},
			{name : 'baby showers '  , description: ''},
			{name : 'Backstreet Boys '  , description: ''},
			{name : 'bad dogs '  , description: ''},
			{name : 'bad haircut '  , description: ''},
			{name : 'bagpipes '  , description: ''},
			{name : 'baked beans'  , description: ''},
			{name : 'baked potatoes'  , description: ''},
			{name : 'baking cookies '  , description: ''},
			{name : 'bald eagles '  , description: ''},
			{name : 'ballerinas'  , description: ''},
			{name : 'Bangkok'  , description: ''},
			{name : 'bankruptcy '  , description: ''},
			{name : 'Barbara Walters'  , description: ''},
			{name : 'barbed wire'  , description: ''},
			{name : 'barfing'  , description: ''},
			{name : 'Barney'  , description: ''},
			{name : 'Bart Simpson'  , description: ''},
			{name : 'Bates Motel '  , description: ''},
			{name : 'Batman '  , description: ''},
			{name : 'bats '  , description: ''},
			{name : 'beach parties '  , description: ''},
			{name : 'Beanie Babies'  , description: ''},
			{name : 'Beauty and the Beast'  , description: ''},
			{name : 'beer bellies '  , description: ''},
			{name : 'Beethoven'  , description: ''},
			{name : 'beets'  , description: ''},
			{name : 'being in love '  , description: ''},
			{name : 'bellbottoms'  , description: ''},
			{name : 'Ben Stiller '  , description: ''},
			{name : 'Berlin - 1945'  , description: ''},
			{name : 'big bang theory '  , description: ''},
			{name : 'big business'  , description: ''},
			{name : 'Big Macs '  , description: ''},
			{name : 'Bigfoot'  , description: ''},
			{name : 'Bill Clinton'  , description: ''},
			{name : 'Bill Gates'  , description: ''},
			{name : 'Bill Murray '  , description: ''},
			{name : 'billboards'  , description: ''},
			{name : 'bingo'  , description: ''},
			{name : 'birdwatching'  , description: ''},
			{name : 'black holes '  , description: ''},
			{name : 'black velvet'  , description: ''},
			{name : 'blizzard'  , description: ''},
			{name : 'blood '  , description: ''},
			{name : 'board games '  , description: ''},
			{name : 'body odor'  , description: ''},
			{name : 'body piercing'  , description: ''},
			{name : 'body surfing '  , description: ''},
			{name : 'bombs'  , description: ''},
			{name : 'bonbons'  , description: ''},
			{name : 'bongos'  , description: ''},
			{name : 'bottled water'  , description: ''},
			{name : 'bounty hunters '  , description: ''},
			{name : 'boxing'  , description: ''},
			{name : 'boy scouts'  , description: ''},
			{name : 'boyfriends'  , description: ''},
			{name : 'Brad Pitt'  , description: ''},
			{name : 'brain surgeons '  , description: ''},
			{name : 'brains  '  , description: ''},
			{name : 'Britney Spears '  , description: ''},
			{name : 'Broadway'  , description: ''},
			{name : 'Bruce Willis '  , description: ''},
			{name : 'bubble gum'  , description: ''},
			{name : 'bubbles'  , description: ''},
			{name : 'bull fight '  , description: ''},
			{name : 'Bullwinkle'  , description: ''},
			{name : 'bumper stickers'  , description: ''},
			{name : 'bungee jumping'  , description: ''},
			{name : 'buying a house '  , description: ''},
			{name : 'cabbage '  , description: ''},
			{name : 'cactus'  , description: ''},
			{name : 'caffeine'  , description: ''},
			{name : 'California '  , description: ''},
			{name : 'camping trips '  , description: ''},
			{name : 'Canada'  , description: ''},
			{name : 'Canadians '  , description: ''},
			{name : 'Captain Kirk'  , description: ''},
			{name : 'car horns '  , description: ''},
			{name : 'Carl Sagan'  , description: ''},
			{name : 'carnival workers '  , description: ''},
			{name : 'Cary Grant '  , description: ''},
			{name : 'Casablanca'  , description: ''},
			{name : 'casinos'  , description: ''},
			{name : 'castles'  , description: ''},
			{name : 'caves'  , description: ''},
			{name : 'Celine Dion '  , description: ''},
			{name : 'cell phones'  , description: ''},
			{name : 'Cesar Chávez '  , description: ''},
			{name : 'chain letters '  , description: ''},
			{name : 'chains'  , description: ''},
			{name : 'Challenger explosion '  , description: ''},
			{name : 'chameleons'  , description: ''},
			{name : 'charging rhinos '  , description: ''},
			{name : 'cheesecake '  , description: ''},
			{name : 'Cher'  , description: ''},
			{name : 'Chicago '  , description: ''},
			{name : 'chicken pox'  , description: ''},
			{name : 'chickens '  , description: ''},
			{name : 'chimpanzees'  , description: ''},
			{name : 'China '  , description: ''},
			{name : 'Chinatown'  , description: ''},
			{name : 'choir boys '  , description: ''},
			{name : 'cholesterol '  , description: ''},
			{name : 'chorus girls '  , description: ''},
			{name : 'Cinco de Mayo'  , description: ''},
			{name : 'Cindy Crawford '  , description: ''},
			{name : 'Clark Gable '  , description: ''},
			{name : 'Claude Monet '  , description: ''},
			{name : 'cleaning the bathroom '  , description: ''},
			{name : 'Cleopatra'  , description: ''},
			{name : 'Clint Eastwood '  , description: ''},
			{name : 'clowns '  , description: ''},
			{name : 'cockroaches'  , description: ''},
			{name : 'coconuts'  , description: ''},
			{name : 'cold pizza'  , description: ''},
			{name : 'communists'  , description: ''},
			{name : 'commuting'  , description: ''},
			{name : 'computer hackers '  , description: ''},
			{name : 'computers'  , description: ''},
			{name : 'Confucius'  , description: ''},
			{name : 'conspiracy theories '  , description: ''},
			{name : 'construction workers '  , description: ''},
			{name : 'corn on the cob'  , description: ''},
			{name : 'Corvettes '  , description: ''},
			{name : 'Count Dracula '  , description: ''},
			{name : 'country music'  , description: ''},
			{name : 'cow-pies '  , description: ''},
			{name : 'crawl space'  , description: ''},
			{name : 'Crazy Horse'  , description: ''},
			{name : 'creamed corn'  , description: ''},
			{name : 'crystal balls '  , description: ''},
			{name : 'Cuba '  , description: ''},
			{name : 'cults'  , description: ''},
			{name : "Custer's Last Stand "  , description: ''},
			{name : 'Danielle Steele '  , description: ''},
			{name : 'Danny DeVito '  , description: ''},
			{name : 'dark alleys '  , description: ''},
			{name : 'Darth Vader'  , description: ''},
			{name : 'dating'  , description: ''},
			{name : 'David Letterman '  , description: ''},
			{name : 'daytime TV '  , description: ''},
			{name : 'Death Valley'  , description: ''},
			{name : 'deer hunting '  , description: ''},
			{name : 'Demi Moore '  , description: ''},
			{name : 'Democrats'  , description: ''},
			{name : 'Denzel Washington '  , description: ''},
			{name : 'Detroit'  , description: ''},
			{name : 'diamonds '  , description: ''},
			{name : 'discos'  , description: ''},
			{name : 'discovering America '  , description: ''},
			{name : 'Disneyland'  , description: ''},
			{name : 'divorce'  , description: ''},
			{name : 'doctors'  , description: ''},
			{name : 'doing the dishes '  , description: ''},
			{name : 'Dolly Parton'  , description: ''},
			{name : 'Dr. Kevorkian '  , description: ''},
			{name : 'Dr. Seuss'  , description: ''},
			{name : 'driving off a cliff '  , description: ''},
			{name : 'duct tape'  , description: ''},
			{name : 'earthquakes'  , description: ''},
			{name : 'earwax '  , description: ''},
			{name : 'earwigs'  , description: ''},
			{name : 'east coast'  , description: ''},
			{name : 'Eddie Murphy '  , description: ''},
			{name : 'Eleanor Roosevelt '  , description: ''},
			{name : 'electric eels '  , description: ''},
			{name : 'electricity '  , description: ''},
			{name : 'elephants'  , description: ''},
			{name : 'Elizabeth Taylor'  , description: ''},
			{name : 'Elvis Presley'  , description: ''},
			{name : 'email'  , description: ''},
			{name : 'Emily Dickinson'  , description: ''},
			{name : 'Ernest Hemingway'  , description: ''},
			{name : 'Europe'  , description: ''},
			{name : 'exorcism'  , description: ''},
			{name : 'eyes4'  , description: ''},
			{name : 'falling down '  , description: ''},
			{name : 'family reunions '  , description: ''},
			{name : 'family vacations '  , description: ''},
			{name : 'family values'  , description: ''},
			{name : 'fast food '  , description: ''},
			{name : 'feathers  '  , description: ''},
			{name : 'feminists'  , description: ''},
			{name : 'festering wounds '  , description: ''},
			{name : 'Fidel Castro'  , description: ''},
			{name : 'firefighters '  , description: ''},
			{name : 'firestorms '  , description: ''},
			{name : 'fireworks'  , description: ''},
			{name : 'first man on the moon '  , description: ''},
			{name : 'flat tire'  , description: ''},
			{name : 'Flipper '  , description: ''},
			{name : 'fly fishing'  , description: ''},
			{name : 'flying monkeys'  , description: ''},
			{name : 'forest fires '  , description: ''},
			{name : 'Fort Knox '  , description: ''},
			{name : 'Frank Lloyd Wright'  , description: ''},
			{name : 'Frank Sinatra'  , description: ''},
			{name : 'freckles'  , description: ''},
			{name : 'freedom8'  , description: ''},
			{name : 'French wines '  , description: ''},
			{name : 'freshwater pearls '  , description: ''},
			{name : 'friction'  , description: ''},
			{name : 'fundraising'  , description: ''},
			{name : 'funerals'  , description: ''},
			{name : 'fur4'  , description: ''},
			{name : 'fuzz'  , description: ''},
			{name : 'gall bladder'  , description: ''},
			{name : 'gang members '  , description: ''},
			{name : 'Garrison Keillor '  , description: ''},
			{name : 'Garth Brooks '  , description: ''},
			{name : 'geishas'  , description: ''},
			{name : 'General George S. Patton '  , description: ''},
			{name : 'genetic engineering'  , description: ''},
			{name : 'George W. Bush'  , description: ''},
			{name : 'George Washington '  , description: ''},
			{name : "Georgia O'Keefe "  , description: ''},
			{name : 'getting a hug '  , description: ''},
			{name : 'ghost towns '  , description: ''},
			{name : 'ghosts '  , description: ''},
			{name : 'giant squid'  , description: ''},
			{name : 'Gila monsters '  , description: ''},
			{name : 'Ginko trees '  , description: ''},
			{name : 'ginseng '  , description: ''},
			{name : 'girlfriends'  , description: ''},
			{name : 'giving a hug '  , description: ''},
			{name : 'glaciers'  , description: ''},
			{name : 'glazed donuts '  , description: ''},
			{name : 'global warming '  , description: ''},
			{name : 'going to church '  , description: ''},
			{name : "going to grandma's "  , description: ''},
			{name : 'going to school '  , description: ''},
			{name : 'going to the dentist '  , description: ''},
			{name : 'going to the gym '  , description: ''},
			{name : 'gold chains '  , description: ''},
			{name : 'goldfish'  , description: ''},
			{name : 'Goldie Hawn '  , description: ''},
			{name : 'golf-ball-sized hail '  , description: ''},
			{name : 'gossip'  , description: ''},
			{name : 'Grace Kelly '  , description: ''},
			{name : 'graffiti  '  , description: ''},
			{name : 'grass skirts '  , description: ''},
			{name : 'grave robbers '  , description: ''},
			{name : 'gravity'  , description: ''},
			{name : 'Greenpeace'  , description: ''},
			{name : 'gym teachers '  , description: ''},
			{name : 'hair transplants '  , description: ''},
			{name : 'hairballs'  , description: ''},
			{name : 'Halloween'  , description: ''},
			{name : 'hand grenades '  , description: ''},
			{name : 'handcuffs '  , description: ''},
			{name : 'hangnails'  , description: ''},
			{name : 'having a baby '  , description: ''},
			{name : 'having an operation '  , description: ''},
			{name : 'Hawaii '  , description: ''},
			{name : 'Helen Keller'  , description: ''},
			{name : 'hiccups'  , description: ''},
			{name : 'high school football '  , description: ''},
			{name : 'high school reunions '  , description: ''},
			{name : 'Hillary Rodham Clinton '  , description: ''},
			{name : 'Hiroshima - 1945'  , description: ''},
			{name : 'HMOs '  , description: ''},
			{name : 'hockey'  , description: ''},
			{name : 'Hollywood'  , description: ''},
			{name : 'homeless shelters '  , description: ''},
			{name : 'Homer Simpson '  , description: ''},
			{name : 'homework'  , description: ''},
			{name : 'Homphrey Bogart '  , description: ''},
			{name : 'hooligans '  , description: ''},
			{name : 'horseback riding'  , description: ''},
			{name : 'hot lava '  , description: ''},
			{name : 'houseguests '  , description: ''},
			{name : 'hummingbirds'  , description: ''},
			{name : 'icebergs'  , description: ''},
			{name : 'in a coma '  , description: ''},
			{name : 'incense9'  , description: ''},
			{name : 'India '  , description: ''},
			{name : 'Indiana Jones '  , description: ''},
			{name : 'Industrial Revolution'  , description: ''},
			{name : 'infomercials'  , description: ''},
			{name : 'inside the sun '  , description: ''},
			{name : 'intellectuals '  , description: ''},
			{name : 'Ireland'  , description: ''},
			{name : 'Israel '  , description: ''},
			{name : 'Italy '  , description: ''},
			{name : 'Jack Nicholson '  , description: ''},
			{name : 'Jack the Ripper'  , description: ''},
			{name : 'Jackie Chan '  , description: ''},
			{name : 'Jacques Cousteau '  , description: ''},
			{name : 'Jamaica'  , description: ''},
			{name : 'James Bond'  , description: ''},
			{name : 'James Dean'  , description: ''},
			{name : 'Japan  '  , description: ''},
			{name : 'Japanese '  , description: ''},
			{name : 'jelly beans'  , description: ''},
			{name : 'Jennifer Lopez '  , description: ''},
			{name : 'Jerry Springer '  , description: ''},
			{name : 'Jesse Jackson'  , description: ''},
			{name : 'Jesse Ventura '  , description: ''},
			{name : 'Jim Carrey '  , description: ''},
			{name : 'Jimmy Stewart '  , description: ''},
			{name : 'Joan of Arc'  , description: ''},
			{name : 'Jodie Foster '  , description: ''},
			{name : 'John F Kennedy '  , description: ''},
			{name : 'John Glenn'  , description: ''},
			{name : 'John Phillip Sousa '  , description: ''},
			{name : 'John Travolta '  , description: ''},
			{name : 'Judge Judy '  , description: ''},
			{name : 'Julia Roberts'  , description: ''},
			{name : 'junk mail'  , description: ''},
			{name : 'Jupiter '  , description: ''},
			{name : 'Katharine Hepburn '  , description: ''},
			{name : 'Keanu Reeves '  , description: ''},
			{name : 'killer whales '  , description: ''},
			{name : 'kilts'  , description: ''},
			{name : 'King Arthur'  , description: ''},
			{name : 'King Henry VIII '  , description: ''},
			{name : 'knock-knock jokes '  , description: ''},
			{name : 'labor unions '  , description: ''},
			{name : 'Large Mouth Bass '  , description: ''},
			{name : 'Las Vegas'  , description: ''},
			{name : 'lawyers '  , description: ''},
			{name : 'leaf blowers '  , description: ''},
			{name : 'leather '  , description: ''},
			{name : 'leeches '  , description: ''},
			{name : 'lemons '  , description: ''},
			{name : "Lenin's Tomb "  , description: ''},
			{name : 'Leonardo da Vinci'  , description: ''},
			{name : 'lightning6'  , description: ''},
			{name : 'loan sharks '  , description: ''},
			{name : 'lobster  '  , description: ''},
			{name : 'local police'  , description: ''},
			{name : 'log cabins '  , description: ''},
			{name : 'lollipops '  , description: ''},
			{name : 'London '  , description: ''},
			{name : 'looking for a job '  , description: ''},
			{name : 'Los Angeles'  , description: ''},
			{name : 'losing your job '  , description: ''},
			{name : 'Lucille Ball '  , description: ''},
			{name : 'machine guns '  , description: ''},
			{name : 'mad cow disease'  , description: ''},
			{name : 'Madame Curie '  , description: ''},
			{name : 'Madonna'  , description: ''},
			{name : 'magic tricks '  , description: ''},
			{name : 'Mahatma Gandhi '  , description: ''},
			{name : 'Manhattan '  , description: ''},
			{name : 'mardi gras'  , description: ''},
			{name : 'Mark Twain'  , description: ''},
			{name : 'marriage4'  , description: ''},
			{name : 'Mars '  , description: ''},
			{name : 'Martha Stewart '  , description: ''},
			{name : 'Martin Luther King, Jr.'  , description: ''},
			{name : 'meat cleavers '  , description: ''},
			{name : 'meatloaf'  , description: ''},
			{name : 'Meg Ryan'  , description: ''},
			{name : 'Mel Gibson'  , description: ''},
			{name : 'men'  , description: ''},
			{name : 'Men in Black '  , description: ''},
			{name : 'Meryl Streep'  , description: ''},
			{name : 'Mexico '  , description: ''},
			{name : 'mice'  , description: ''},
			{name : 'Michael Jackson'  , description: ''},
			{name : 'Michael Jordan'  , description: ''},
			{name : 'Michelangelo '  , description: ''},
			{name : 'Michele Pfeifer '  , description: ''},
			{name : 'Microsoft'  , description: ''},
			{name : 'mid-life crisis '  , description: ''},
			{name : 'Mike Tyson '  , description: ''},
			{name : 'Miles Davis'  , description: ''},
			{name : 'milk'  , description: ''},
			{name : 'Milk Duds'  , description: ''},
			{name : 'mirrors '  , description: ''},
			{name : 'mold'  , description: ''},
			{name : 'money'  , description: ''},
			{name : 'morticians '  , description: ''},
			{name : 'mosquitos'  , description: ''},
			{name : 'motorcycles'  , description: ''},
			{name : 'Mount Rushmore'  , description: ''},
			{name : 'MTV'  , description: ''},
			{name : 'mud4'  , description: ''},
			{name : 'mudslides '  , description: ''},
			{name : 'Muhammad Ali'  , description: ''},
			{name : 'musicals '  , description: ''},
			{name : 'my bank account '  , description: ''},
			{name : 'my bathroom '  , description: ''},
			{name : 'my bedroom'  , description: ''},
			{name : 'my body '  , description: ''},
			{name : 'my boss'  , description: ''},
			{name : 'my dreams'  , description: ''},
			{name : 'my family '  , description: ''},
			{name : 'my first kiss '  , description: ''},
			{name : 'my friends'  , description: ''},
			{name : 'my future '  , description: ''},
			{name : 'my hair '  , description: ''},
			{name : 'my high school prom '  , description: ''},
			{name : 'my job '  , description: ''},
			{name : 'my love life '  , description: ''},
			{name : 'my mind'  , description: ''},
			{name : 'my neighborhood '  , description: ''},
			{name : "my parents' house "  , description: ''},
			{name : 'my past '  , description: ''},
			{name : 'my personality '  , description: ''},
			{name : 'my refrigerator '  , description: ''},
			{name : 'my sixteenth birthday '  , description: ''},
			{name : 'Napoleon Bonaparte'  , description: ''},
			{name : 'NASCAR '  , description: ''},
			{name : 'Neil Simon '  , description: ''},
			{name : 'New Orleans'  , description: ''},
			{name : 'new shoes'  , description: ''},
			{name : 'New York City '  , description: ''},
			{name : 'Niagara Falls'  , description: ''},
			{name : 'Nicholas Cage '  , description: ''},
			{name : 'ninjas'  , description: ''},
			{name : 'Nobel Peace Prize '  , description: ''},
			{name : 'noisy neighbors'  , description: ''},
			{name : 'Norman Rockwell'  , description: ''},
			{name : 'nuclear power plants '  , description: ''},
			{name : 'NYPD'  , description: ''},
			{name : 'oil spills '  , description: ''},
			{name : 'olive oil '  , description: ''},
			{name : 'online shopping '  , description: ''},
			{name : 'Oprah Winfrey'  , description: ''},
			{name : 'oral surgery '  , description: ''},
			{name : 'oranges '  , description: ''},
			{name : 'outlet malls '  , description: ''},
			{name : 'oxygen'  , description: ''},
			{name : 'Pablo Picasso'  , description: ''},
			{name : 'parenting'  , description: ''},
			{name : 'Paris'  , description: ''},
			{name : 'paying bills '  , description: ''},
			{name : 'paying taxes '  , description: ''},
			{name : 'penguins'  , description: ''},
			{name : 'picking your nose '  , description: ''},
			{name : 'pigeons'  , description: ''},
			{name : 'pigs'  , description: ''},
			{name : 'piranha'  , description: ''},
			{name : 'pirates '  , description: ''},
			{name : 'pitbulls '  , description: ''},
			{name : 'plane crashes '  , description: ''},
			{name : 'plastic'  , description: ''},
			{name : 'playing chess '  , description: ''},
			{name : 'poison ivy'  , description: ''},
			{name : 'Pokemon'  , description: ''},
			{name : 'pond scum '  , description: ''},
			{name : 'poodles'  , description: ''},
			{name : 'popcorn4'  , description: ''},
			{name : 'Porsche Boxster '  , description: ''},
			{name : 'postal workers '  , description: ''},
			{name : 'power tools'  , description: ''},
			{name : 'Prince Charming'  , description: ''},
			{name : 'Princess Di '  , description: ''},
			{name : 'pro wrestling '  , description: ''},
			{name : 'psychiatrists'  , description: ''},
			{name : 'psychics '  , description: ''},
			{name : 'public radio '  , description: ''},
			{name : 'Puff Daddy '  , description: ''},
			{name : 'pulling weeds '  , description: ''},
			{name : 'pumping iron'  , description: ''},
			{name : 'pushups '  , description: ''},
			{name : 'pyromaniacs '  , description: ''},
			{name : 'Quentin Tarantino'  , description: ''},
			{name : 'quicksand'  , description: ''},
			{name : 'ragweed'  , description: ''},
			{name : 'rain '  , description: ''},
			{name : 'rainbows'  , description: ''},
			{name : 'rappers'  , description: ''},
			{name : 'reading a book '  , description: ''},
			{name : 'recreational vehicles '  , description: ''},
			{name : 'recycling'  , description: ''},
			{name : 'red raspberries '  , description: ''},
			{name : 'rednecks'  , description: ''},
			{name : 'redwood forests '  , description: ''},
			{name : 'reggae music '  , description: ''},
			{name : 'Regis Philbin '  , description: ''},
			{name : 'remote controls '  , description: ''},
			{name : 'republicans'  , description: ''},
			{name : 'Richard Nixon'  , description: ''},
			{name : 'road trips '  , description: ''},
			{name : 'roadkill'  , description: ''},
			{name : 'Robert De Niro '  , description: ''},
			{name : 'Robin Williams '  , description: ''},
			{name : 'rock and roll '  , description: ''},
			{name : 'rock concert '  , description: ''},
			{name : 'rocket scientists '  , description: ''},
			{name : 'Rocky Mountains'  , description: ''},
			{name : 'rolling the car '  , description: ''},
			{name : 'Roman numberals '  , description: ''},
			{name : 'Romeo and Juliet '  , description: ''},
			{name : 'root beer floats '  , description: ''},
			{name : 'Rosa Parks'  , description: ''},
			{name : "Rosie O'Donnell "  , description: ''},
			{name : 'rubber gloves'  , description: ''},
			{name : 'running a marathon '  , description: ''},
			{name : 'Rush Limbaugh'  , description: ''},
			{name : 'Russia '  , description: ''},
			{name : 'rust '  , description: ''},
			{name : 'Saddam Hussein '  , description: ''},
			{name : 'sailors'  , description: ''},
			{name : 'salads'  , description: ''},
			{name : 'salsa dancing '  , description: ''},
			{name : 'Salvador Dali'  , description: ''},
			{name : 'Samuel L. Jackson '  , description: ''},
			{name : 'San Francisco '  , description: ''},
			{name : 'Saturday cartoons '  , description: ''},
			{name : 'Saturn'  , description: ''},
			{name : 'scavenger hunts '  , description: ''},
			{name : 'scene of the crime'  , description: ''},
			{name : "Schindler's List "  , description: ''},
			{name : 'school cafeteria '  , description: ''},
			{name : 'science fair projects '  , description: ''},
			{name : 'science fiction '  , description: ''},
			{name : 'screeching '  , description: ''},
			{name : 'Sean Connery '  , description: ''},
			{name : 'secret societies '  , description: ''},
			{name : 'Shania Twain '  , description: ''},
			{name : 'sharks '  , description: ''},
			{name : 'shopping malls '  , description: ''},
			{name : 'silk'  , description: ''},
			{name : 'silly putty'  , description: ''},
			{name : 'six pack'  , description: ''},
			{name : 'skateboarding'  , description: ''},
			{name : 'skiing '  , description: ''},
			{name : 'skunks'  , description: ''},
			{name : 'skydiving'  , description: ''},
			{name : 'sleeping pills '  , description: ''},
			{name : 'slivers'  , description: ''},
			{name : 'sloppy joes '  , description: ''},
			{name : 'snakes'  , description: ''},
			{name : 'snow'  , description: ''},
			{name : 'social security'  , description: ''},
			{name : 'socks'  , description: ''},
			{name : 'South Africa'  , description: ''},
			{name : 'South Park'  , description: ''},
			{name : 'soy sauce'  , description: ''},
			{name : 'spam'  , description: ''},
			{name : 'speeding tickets '  , description: ''},
			{name : 'spiders'  , description: ''},
			{name : 'Spike Lee '  , description: ''},
			{name : 'spilled milk '  , description: ''},
			{name : 'spit'  , description: ''},
			{name : 'spontaneous combustion'  , description: ''},
			{name : 'sport utility vehicles '  , description: ''},
			{name : 'sports channels '  , description: ''},
			{name : 'star fruit'  , description: ''},
			{name : 'Starry Night '  , description: ''},
			{name : 'state fairs '  , description: ''},
			{name : 'steak and potatoes '  , description: ''},
			{name : 'Stephen King'  , description: ''},
			{name : 'Steve Martin '  , description: ''},
			{name : 'Steven Spielberg '  , description: ''},
			{name : 'Stonehenge'  , description: ''},
			{name : 'strawberry shortcake '  , description: ''},
			{name : 'stubbed toes '  , description: ''},
			{name : 'stun guns '  , description: ''},
			{name : 'stunt people '  , description: ''},
			{name : 'summer camp'  , description: ''},
			{name : 'Sunday drivers '  , description: ''},
			{name : 'Superman'  , description: ''},
			{name : 'supermodels '  , description: ''},
			{name : 'surfing the net '  , description: ''},
			{name : 'sushi4'  , description: ''},
			{name : 'Swiss bank accounts '  , description: ''},
			{name : 'Swiss cheese'  , description: ''},
			{name : 'Swiss chocolate '  , description: ''},
			{name : 'taking a bath '  , description: ''},
			{name : 'talk radio '  , description: ''},
			{name : 'teachers'  , description: ''},
			{name : 'telemarketers'  , description: ''},
			{name : 'televangelists '  , description: ''},
			{name : 'television4'  , description: ''},
			{name : 'telling the truth '  , description: ''},
			{name : 'Thanksgiving Day'  , description: ''},
			{name : 'The 21st century '  , description: ''},
			{name : 'The  1920s '  , description: ''},
			{name : 'The  1950s '  , description: ''},
			{name : 'The  1960s '  , description: ''},
			{name : 'the  1970s '  , description: ''},
			{name : 'The  1980s '  , description: ''},
			{name : 'The Academy Awards '  , description: ''},
			{name : 'the beach'  , description: ''},
			{name : 'The Beatles '  , description: ''},
			{name : 'the CIA '  , description: ''},
			{name : 'The Cold War '  , description: ''},
			{name : 'the common loon '  , description: ''},
			{name : 'The Dallas Cowboys '  , description: ''},
			{name : 'the dump '  , description: ''},
			{name : 'The Eiffel Tower '  , description: ''},
			{name : 'the electric chair '  , description: ''},
			{name : 'the end of the world '  , description: ''},
			{name : 'the everglades '  , description: ''},
			{name : 'the far left'  , description: ''},
			{name : 'the far right'  , description: ''},
			{name : 'The FBI '  , description: ''},
			{name : 'the first day of school '  , description: ''},
			{name : 'The French Riviera '  , description: ''},
			{name : 'The Godfather '  , description: ''},
			{name : 'The Grand Canyon '  , description: ''},
			{name : 'The Grateful Dead'  , description: ''},
			{name : 'The Great Chicago Fire '  , description: ''},
			{name : 'The Great Depression '  , description: ''},
			{name : 'The Green Bay Packers '  , description: ''},
			{name : 'The Gulf War '  , description: ''},
			{name : 'The Indy'  , description: ''},
			{name : 'The Internet '  , description: ''},
			{name : 'The IRS '  , description: ''},
			{name : 'The JFK Assassination '  , description: ''},
			{name : 'The Land of Oz '  , description: ''},
			{name : 'The Little Mermaid '  , description: ''},
			{name : 'the mafia '  , description: ''},
			{name : 'The Marx Brothers '  , description: ''},
			{name : 'The Metric System '  , description: ''},
			{name : 'The Midwest '  , description: ''},
			{name : 'The Milky Way '  , description: ''},
			{name : 'The Mississippi River '  , description: ''},
			{name : 'The National Enquirer '  , description: ''},
			{name : 'The NRA '  , description: ''},
			{name : 'The NY Yankees '  , description: ''},
			{name : 'the ocean '  , description: ''},
			{name : 'The Old Man and the Sea '  , description: ''},
			{name : 'The Olympics '  , description: ''},
			{name : 'the opera '  , description: ''},
			{name : 'the ozone layer'  , description: ''},
			{name : 'The Pentagon'  , description: ''},
			{name : 'the pyramids '  , description: ''},
			{name : 'The Renaissance '  , description: ''},
			{name : 'The Rolling Stones'  , description: ''},
			{name : 'The San Andreas Fault '  , description: ''},
			{name : 'The Smithsonian Institution '  , description: ''},
			{name : 'The South '  , description: ''},
			{name : 'The Statue of Liberty '  , description: ''},
			{name : 'the sunrise '  , description: ''},
			{name : 'The Super Bowl '  , description: ''},
			{name : 'The Supreme Court '  , description: ''},
			{name : 'The Three Tenors '  , description: ''},
			{name : 'The Titanic'  , description: ''},
			{name : 'the universe'  , description: ''},
			{name : 'The Vatican '  , description: ''},
			{name : 'The Vietnam Memorial '  , description: ''},
			{name : 'The Williams Sisters '  , description: ''},
			{name : 'The Wright Brothers '  , description: ''},
			{name : 'The YMCA '  , description: ''},
			{name : 'Thomas Edison'  , description: ''},
			{name : 'thunder'  , description: ''},
			{name : 'Tibet'  , description: ''},
			{name : 'ticks'  , description: ''},
			{name : 'tidal waves '  , description: ''},
			{name : 'Tiger Woods '  , description: ''},
			{name : 'toasters '  , description: ''},
			{name : 'toates marshmallows '  , description: ''},
			{name : 'toes '  , description: ''},
			{name : 'Tom Cruise '  , description: ''},
			{name : 'Tom Hanks '  , description: ''},
			{name : 'top of a roller coaster '  , description: ''},
			{name : 'tornadoes'  , description: ''},
			{name : 'toys '  , description: ''},
			{name : 'trailer parks '  , description: ''},
			{name : 'trampolines '  , description: ''},
			{name : 'tree huggers '  , description: ''},
			{name : 'truck stops '  , description: ''},
			{name : 'Tyrannosaurus Rex '  , description: ''},
			{name : 'underwear '  , description: ''},
			{name : 'United Nations'  , description: ''},
			{name : 'UV rays '  , description: ''},
			{name : 'vacation'  , description: ''},
			{name : 'vampires'  , description: ''},
			{name : 'Victorian England '  , description: ''},
			{name : 'video games'  , description: ''},
			{name : 'Vietnam - 1968'  , description: ''},
			{name : 'Vincent Van Gogh '  , description: ''},
			{name : 'violins'  , description: ''},
			{name : 'VW Beetles '  , description: ''},
			{name : 'Waco, Texas '  , description: ''},
			{name : 'Wall Street '  , description: ''},
			{name : 'Walt Disney'  , description: ''},
			{name : 'warts'  , description: ''},
			{name : 'watching football '  , description: ''},
			{name : 'water beds '  , description: ''},
			{name : 'water parks '  , description: ''},
			{name : 'waterfalls'  , description: ''},
			{name : 'watermelons'  , description: ''},
			{name : 'weddings'  , description: ''},
			{name : 'wheat'  , description: ''},
			{name : 'Wheel of Fortune'  , description: ''},
			{name : 'whipped cream '  , description: ''},
			{name : 'whips '  , description: ''},
			{name : 'Whoopi Goldberg '  , description: ''},
			{name : 'Will Smith '  , description: ''},
			{name : 'William Shakespeare'  , description: ''},
			{name : 'Wimbledon'  , description: ''},
			{name : 'wind surfing '  , description: ''},
			{name : 'wine tasting'  , description: ''},
			{name : 'winning the lottery '  , description: ''},
			{name : 'witch hunts '  , description: ''},
			{name : 'women'  , description: ''},
			{name : "women's soccer"  , description: ''},
			{name : 'wood chippers '  , description: ''},
			{name : 'Woodstock'  , description: ''},
			{name : 'Woody Allen'  , description: ''},
			{name : 'worms'  , description: ''},
			{name : 'X-ray vision'  , description: ''},
			{name : 'X-rays '  , description: ''},
			{name : 'Yellowston Park '  , description: ''},
			{name : 'zen'  , description: ''},
			{name : 'zucchini'  , description: ''},
		]
	}
}
function applestoapplesJoinGame(username, socketId, state) {
	if (!state.players) return;

	//? Add the player to the state
	state.players.push({
		username,
		socketId,
		ready: false,
		judge: false,
		score: 0,
	});
	return state;
}
function applestoapplesReadyUp(socketId, state) {
	if (!state.players) return;
console.log('inside utility for ready up');
	for (let i= 0; i < state.players.length; i++) {
		if (state.players[i].socketId=== socketId) {
			state.players[i].ready= true;
			return;
		}
	}
}
